"""Zanim's compact authoring API.

The root package contains objects and values used to describe scenes. Scheduler,
bound-handle, wire-format and render implementation types live in submodules.
"""

from ._version import __version__
from .audio import Audio
from .camera import Camera2D
from .camera3d import Camera3D
from .constants import (
    BLACK,
    BLUE,
    CYAN,
    DEGREES,
    DOWN,
    GRAY,
    GREEN,
    LEFT,
    MUTED,
    ORANGE,
    ORIGIN,
    PI,
    PINK,
    PURPLE,
    RED,
    RIGHT,
    TAU,
    TRANSPARENT,
    UP,
    WHITE,
    YELLOW,
)
from .dynamic import DynamicNumber, NumberFormat
from .errors import MediaError, NativeError, PreviewError, ZanimError
from .formula import (
    FormulaInstance,
    FormulaLiteral,
    FormulaTemplate,
    MatrixSlot,
    NumberSlot,
    ObjectSlot,
    ScriptSlots,
)
from .geometry import Color, StrokeStyle, Style
from .group import Group
from .layout import (
    BOTTOM,
    BOTTOM_LEFT,
    BOTTOM_RIGHT,
    CENTER,
    LEFT_CENTER,
    RIGHT_CENTER,
    TOP,
    TOP_LEFT,
    TOP_RIGHT,
    Anchor,
    Column,
    Frame,
    Grid,
    Row,
)
from .mesh3d import Box3D, Cube3D, Surface3D
from .plot import Axes
from .raster import GIF, Image, Video
from .scene import Scene
from .shapes import (
    Arc,
    Arrow,
    Circle,
    CubicBezier,
    Dot,
    Ellipse,
    Line,
    NumberLine,
    Polygon,
    Polyline,
    Rectangle,
    RegularPolygon,
    Shape,
    Square,
)
from .space import (
    LOCAL,
    PARENT,
    SE2,
    WORLD,
    Canvas,
    Transform2D,
    TransformFrame,
    Vec2,
    affine2d,
    pose2d,
)
from .space3d import SO3, Transform3D, Vec3
from .svg import load_svg
from .timeline import Easing
from .typst import Math, Text

__all__ = [
    "__version__",
    "ZanimError",
    "PreviewError",
    "MediaError",
    "NativeError",
    "Scene",
    "Canvas",
    "Shape",
    "Circle",
    "Square",
    "Rectangle",
    "Ellipse",
    "Arc",
    "RegularPolygon",
    "Line",
    "Polyline",
    "Polygon",
    "CubicBezier",
    "Dot",
    "Arrow",
    "NumberLine",
    "Group",
    "Text",
    "Math",
    "Color",
    "Style",
    "StrokeStyle",
    "BLUE",
    "GREEN",
    "RED",
    "YELLOW",
    "ORANGE",
    "PURPLE",
    "PINK",
    "CYAN",
    "WHITE",
    "GRAY",
    "MUTED",
    "BLACK",
    "TRANSPARENT",
    "PI",
    "TAU",
    "DEGREES",
    "Vec2",
    "Transform2D",
    "TransformFrame",
    "SE2",
    "affine2d",
    "pose2d",
    "LOCAL",
    "PARENT",
    "WORLD",
    "ORIGIN",
    "RIGHT",
    "LEFT",
    "UP",
    "DOWN",
    "Anchor",
    "Frame",
    "Row",
    "Column",
    "Grid",
    "CENTER",
    "TOP",
    "BOTTOM",
    "LEFT_CENTER",
    "RIGHT_CENTER",
    "TOP_LEFT",
    "TOP_RIGHT",
    "BOTTOM_LEFT",
    "BOTTOM_RIGHT",
    "Easing",
    "Camera2D",
    "Axes",
    "load_svg",
    "DynamicNumber",
    "NumberFormat",
    "FormulaInstance",
    "FormulaLiteral",
    "FormulaTemplate",
    "MatrixSlot",
    "NumberSlot",
    "ObjectSlot",
    "ScriptSlots",
    "Image",
    "GIF",
    "Video",
    "Audio",
    "Camera3D",
    "Vec3",
    "Transform3D",
    "SO3",
    "Box3D",
    "Cube3D",
    "Surface3D",
]
