"""Zanim's public authoring API.

Define class-based scenes with ``Scene.setup()`` for raw declarations and initial
layout, then ``Scene.construct()`` for Scene ownership and timeline authoring. The
root package exposes the objects and values used for authoring; scheduler, bound
handle, wire-format, and render implementation types live in submodules.
"""

from ._version import __version__
from .audio import Audio
from .boolean import BooleanShape, Difference, Exclusion, Intersection, Union
from .camera import Camera2D
from .camera3d import Camera3D, Camera3DState
from .constants import (
    BLACK,
    BLUE,
    CYAN,
    DEGREES,
    DEFAULT_STROKE_WIDTH,
    DOWN,
    GRAY,
    GREEN,
    LEFT,
    MUTED,
    ORANGE,
    ORIGIN,
    PI,
    PINK,
    PURPLE,
    RED,
    RIGHT,
    TAU,
    TRANSPARENT,
    UP,
    WHITE,
    YELLOW,
)
from .dynamic import DynamicNumber, NumberFormat
from .errors import MediaError, NativeError, PreviewError, ZanimError
from .expression import TIME, ScalarExpr, X
from .formula import (
    FormulaInstance,
    FormulaLiteral,
    FormulaTemplate,
    MatrixSlot,
    NumberSlot,
    ObjectSlot,
    ScriptSlots,
)
from .fourier import FourierEpicycles, FourierTerm
from .fractal import JuliaSet, MandelbrotSet
from .geometry import Color, StrokeStyle, Style
from .group import Group
from .group3d import Group3D
from .infinite import ComplexMappedGrid, InfiniteGrid, InfiniteLine, NumberPlane
from .ir import (
    SceneIRUnsupported,
    load_scene_ir,
    read_scene_ir,
    scene_from_ir,
    scene_to_ir,
    write_scene_ir,
)
from .layout import (
    BOTTOM,
    BOTTOM_LEFT,
    BOTTOM_RIGHT,
    CENTER,
    LEFT_CENTER,
    RIGHT_CENTER,
    TOP,
    TOP_LEFT,
    TOP_RIGHT,
    Anchor,
    Column,
    Frame,
    Grid,
    Row,
)
from .mesh3d import Box3D, Cube3D, Surface3D
from .plot import Axes, DynamicGeometryObject2D, FunctionPlot
from .raster import ArrayImage, GIF, Image, SceneViewport, Video
from .scene import Scene
from .shapes import (
    Arc,
    Brace,
    Arrow,
    Circle,
    CubicBezier,
    Dot,
    Ellipse,
    Line,
    NumberLine,
    Polygon,
    Polyline,
    Rectangle,
    RegularPolygon,
    Shape,
    Square,
    SurroundingRectangle,
)
from .simulation import Simulation
from .space import (
    LOCAL,
    PARENT,
    SE2,
    WORLD,
    Canvas,
    Transform2D,
    TransformFrame,
    Vec2,
    affine2d,
    pose2d,
)
from .space3d import SE3, SO3, Transform3D, Vec3, pose3d
from .svg import load_svg
from .timeline import Easing
from .typst import Math, Text
from .value import ScalarValue
from .vector_field import DynamicVectorField, VectorField, VectorSample

__all__ = [
    "__version__",
    "ZanimError",
    "PreviewError",
    "MediaError",
    "NativeError",
    "Scene",
    "SceneViewport",
    "Exclusion",
    "Difference",
    "Union",
    "Intersection",
    "BooleanShape",
    "Simulation",
    "VectorField",
    "DynamicVectorField",
    "VectorSample",
    "SceneIRUnsupported",
    "scene_to_ir",
    "scene_from_ir",
    "write_scene_ir",
    "read_scene_ir",
    "load_scene_ir",
    "Canvas",
    "Shape",
    "Circle",
    "Square",
    "SurroundingRectangle",
    "Rectangle",
    "Ellipse",
    "Arc",
    "Brace",
    "RegularPolygon",
    "Line",
    "InfiniteLine",
    "InfiniteGrid",
    "NumberPlane",
    "ComplexMappedGrid",
    "MandelbrotSet",
    "JuliaSet",
    "FourierTerm",
    "FourierEpicycles",
    "Polyline",
    "Polygon",
    "CubicBezier",
    "Dot",
    "Arrow",
    "NumberLine",
    "Group",
    "Group3D",
    "Text",
    "Math",
    "Color",
    "Style",
    "StrokeStyle",
    "BLUE",
    "GREEN",
    "RED",
    "YELLOW",
    "ORANGE",
    "PURPLE",
    "PINK",
    "CYAN",
    "WHITE",
    "GRAY",
    "MUTED",
    "BLACK",
    "TRANSPARENT",
    "PI",
    "TAU",
    "DEGREES",
    "DEFAULT_STROKE_WIDTH",
    "Vec2",
    "Transform2D",
    "TransformFrame",
    "SE2",
    "SE3",
    "affine2d",
    "pose2d",
    "LOCAL",
    "PARENT",
    "WORLD",
    "ORIGIN",
    "RIGHT",
    "LEFT",
    "UP",
    "DOWN",
    "Anchor",
    "Frame",
    "Row",
    "Column",
    "Grid",
    "CENTER",
    "TOP",
    "BOTTOM",
    "LEFT_CENTER",
    "RIGHT_CENTER",
    "TOP_LEFT",
    "TOP_RIGHT",
    "BOTTOM_LEFT",
    "BOTTOM_RIGHT",
    "Easing",
    "Camera2D",
    "Axes",
    "ScalarExpr",
    "X",
    "TIME",
    "FunctionPlot",
    "ScalarValue",
    "DynamicGeometryObject2D",
    "load_svg",
    "DynamicNumber",
    "NumberFormat",
    "FormulaInstance",
    "FormulaLiteral",
    "FormulaTemplate",
    "MatrixSlot",
    "NumberSlot",
    "ObjectSlot",
    "ScriptSlots",
    "Image",
    "GIF",
    "Video",
    "ArrayImage",
    "Audio",
    "Camera3D",
    "Camera3DState",
    "Vec3",
    "Transform3D",
    "pose3d",
    "SO3",
    "Box3D",
    "Cube3D",
    "Surface3D",
]
