import {Scene,CustomObject2D,Text,Transform2D,WHITE,MUTED,BLUE,GREEN,RED,ORANGE,YELLOW,CYAN,PINK,PURPLE,GRAY,PI,TAU} from '../src/zanim.js';
const rgba=(hex,a=.7)=>hex.startsWith('#')?`${hex}${Math.round(a*255).toString(16).padStart(2,'0')}`:hex;
const T=(x=0,y=0)=>Transform2D.translation(x,y);
function header(scene,title,sub=''){scene.add(new Text(title,{fontSize:33,transform:T(0,3.16),zIndex:30}));if(sub)scene.add(new Text(sub,{fontSize:18,color:MUTED,transform:T(0,2.72),zIndex:30}));}
function final(scene,d){scene.duration=d;scene.cursor=d;scene.seek(0);return scene;}
function path(ctx,r,pts,stroke=WHITE,width=2,close=false,fill=null){if(!pts.length)return;ctx.beginPath();pts.forEach((p,i)=>{const d=r.toDevice(...p);i?ctx.lineTo(...d):ctx.moveTo(...d)});if(close)ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width*r.dpr;ctx.stroke()}}
function label(ctx,r,x,y,text,color=MUTED,size=16){const d=r.toDevice(x,y);ctx.fillStyle=color;ctx.font=`${size*r.dpr}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,d[0],d[1]);}

export function frame_effect_example(renderer){const scene=new Scene(renderer);header(scene,'Frame effect','a child Scene becomes a time-addressable raster, then receives a frame-space effect');scene.add(new CustomObject2D(({ctx,renderer:r,time})=>{const p=(Math.sin(time*1.5)+1)/2;for(let yy=-9;yy<=9;yy++)for(let xx=-15;xx<=15;xx++){const x=xx*.34,y=yy*.34-.35,wave=.14*Math.sin(xx*.8+time*2)+.10*Math.cos(yy*.7-time),d=r.toDevice(x+wave*p,y);ctx.save();ctx.translate(...d);ctx.rotate(.18*Math.sin(time+xx*.2));ctx.fillStyle=(xx+yy)&1?rgba(BLUE,.72):rgba(PINK,.68);ctx.fillRect(-.13*r.unitSize,-.13*r.unitSize,.26*r.unitSize,.26*r.unitSize);ctx.restore();}label(ctx,r,0,-3.0,'frame-space deformation is evaluated from absolute time',YELLOW,17);}));return final(scene,6);}

export function mask_example(renderer){const scene=new Scene(renderer);header(scene,'Alpha mask','content and mask are independent random-access sources');scene.add(new CustomObject2D(({ctx,renderer:r,time})=>{const mx=-3+6*((time/6)%1),my=.45*Math.sin(time*1.7),mr=.85+.4*(.5+.5*Math.sin(time));const drawContent=()=>{for(let i=0;i<9;i++){const a=TAU*i/9+time*.2,x=2*Math.cos(a),y=1.45*Math.sin(a)-.35,d=r.toDevice(x,y);ctx.beginPath();ctx.arc(d[0],d[1],.35*r.unitSize,0,TAU);ctx.fillStyle=[BLUE,GREEN,ORANGE,PINK,PURPLE][i%5];ctx.fill();}const d=r.toDevice(0,-.3);ctx.save();ctx.translate(...d);ctx.rotate(-time*.25);ctx.fillStyle=rgba(CYAN,.55);ctx.fillRect(-2.5*r.unitSize,-.18*r.unitSize,5*r.unitSize,.36*r.unitSize);ctx.restore();};ctx.save();const m=r.toDevice(mx,my-.35);ctx.beginPath();ctx.arc(m[0],m[1],mr*r.unitSize,0,TAU);ctx.clip();drawContent();ctx.restore();ctx.strokeStyle=rgba(WHITE,.5);ctx.lineWidth=2*r.dpr;ctx.beginPath();ctx.arc(m[0],m[1],mr*r.unitSize,0,TAU);ctx.stroke();label(ctx,r,0,-2.75,'moving aperture clips the independently animated content',MUTED,16);}));return final(scene,6.2);}

export function suite(renderer){const scene=new Scene(renderer);header(scene,'JAnim API demonstration','geometry · transforms · paths · dynamic values · axes · vector-like data');scene.add(new CustomObject2D(({ctx,renderer:r,time})=>{const section=Math.floor(time/1.4)%5,q=(time%1.4)/1.4;const names=['Geometry','Transforms','Dynamic path','Axes + graph','Vector reuse'];label(ctx,r,0,2.15,names[section],YELLOW,20);if(section===0){for(const [x,kind,c] of [[-3,'circle',BLUE],[0,'square',GREEN],[3,'triangle',ORANGE]]){const d=r.toDevice(x,-.45);ctx.fillStyle=rgba(c,.78);ctx.strokeStyle=WHITE;ctx.lineWidth=2*r.dpr;ctx.beginPath();if(kind==='circle')ctx.arc(d[0],d[1],.72*r.unitSize,0,TAU);else if(kind==='square')ctx.rect(d[0]-.7*r.unitSize,d[1]-.7*r.unitSize,1.4*r.unitSize,1.4*r.unitSize);else{ctx.moveTo(...r.toDevice(x,0.4));ctx.lineTo(...r.toDevice(x-.9,-1.1));ctx.lineTo(...r.toDevice(x+.9,-1.1));ctx.closePath()}ctx.fill();ctx.stroke()}}else if(section===1){for(let i=0;i<5;i++){const a=i*TAU/5+q*PI,x=2.4*Math.cos(a),y=1.4*Math.sin(a)-.4,d=r.toDevice(x,y);ctx.save();ctx.translate(...d);ctx.rotate(-a);ctx.fillStyle=rgba([BLUE,GREEN,ORANGE,PINK,PURPLE][i],.8);ctx.fillRect(-.35*r.unitSize,-.35*r.unitSize,.7*r.unitSize,.7*r.unitSize);ctx.restore()}}else if(section===2){const pts=[];for(let i=0;i<=220;i++){const x=-4+8*i/220,y=.75*Math.sin(x*1.4+q*TAU)+.25*Math.sin(x*4-q*PI)-.4;pts.push([x,y])}path(ctx,r,pts,CYAN,3)}else if(section===3){ctx.strokeStyle=rgba(GRAY,.4);ctx.lineWidth=r.dpr;for(let i=-4;i<=4;i++){path(ctx,r,[[-5,i*.5],[5,i*.5]],rgba(GRAY,.16),1);path(ctx,r,[[i,-2.3],[i,2]],rgba(GRAY,.16),1)}path(ctx,r,[[-5,0],[5,0]],WHITE,1.5);path(ctx,r,[[0,-2.3],[0,2]],WHITE,1.5);const pts=[];for(let i=0;i<=250;i++){const x=-4.7+9.4*i/250;pts.push([x,.4*Math.sin(1.6*x)+.08*x*x-.6])}path(ctx,r,pts,PINK,3)}else{const heart=[];for(let i=0;i<=220;i++){const a=TAU*i/220;heart.push([1.4*Math.sin(a)**3,(13*Math.cos(a)-5*Math.cos(2*a)-2*Math.cos(3*a)-Math.cos(4*a))/10])}for(const [dx,c,rot] of [[-2.4,PINK,.2],[2.4,CYAN,-.35]]){const co=Math.cos(rot),si=Math.sin(rot);path(ctx,r,heart.map(([x,y])=>[dx+.72*(co*x-si*y),-.4+.72*(si*x+co*y)]),c,3)}}}));return final(scene,7.2);}

function rot3([x,y,z],ax,ay){let cy=Math.cos(ay),sy=Math.sin(ay);[x,z]=[cy*x+sy*z,-sy*x+cy*z];let cx=Math.cos(ax),sx=Math.sin(ax);[y,z]=[cx*y-sx*z,sx*y+cx*z];return[x,y,z]}
function proj(p,ax,ay,ox,oy,s=1){let[x,y,z]=rot3(p,ax,ay);const k=1/(1+.12*z);return[ox+x*k*s,oy+y*k*s]}
export function three_d_shapes_example(renderer){const scene=new Scene(renderer);header(scene,'3D shapes','boxes · sphere wireframe · torus · surface, software-projected in the prototype');scene.add(new CustomObject2D(({ctx,renderer:r,time})=>{const ay=time*.65,ax=.45;const boxVerts=[];for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])boxVerts.push([x,y,z]);for(let i=0;i<8;i++)for(let j=i+1;j<8;j++){let d=0;for(let k=0;k<3;k++)d+=Math.abs(boxVerts[i][k]-boxVerts[j][k]);if(d===2)path(ctx,r,[proj(boxVerts[i],ax,ay,-3.5,.55,.7),proj(boxVerts[j],ax,ay,-3.5,.55,.7)],BLUE,2)}for(let lat=-4;lat<=4;lat++){const pts=[];const ph=lat*PI/10;for(let i=0;i<=60;i++){const th=TAU*i/60;pts.push(proj([Math.cos(ph)*Math.cos(th),Math.sin(ph),Math.cos(ph)*Math.sin(th)],ax,-ay*.8,-1.15,.45,.82))}path(ctx,r,pts,CYAN,1)}for(let j=0;j<9;j++){const pts=[];const v=TAU*j/9;for(let i=0;i<=70;i++){const u=TAU*i/70,R=1,r0=.35;pts.push(proj([(R+r0*Math.cos(v))*Math.cos(u),r0*Math.sin(v),(R+r0*Math.cos(v))*Math.sin(u)],ax,ay*.7,1.45,.45,.65))}path(ctx,r,pts,PINK,1)}for(let z=-5;z<=5;z++){const pts=[];for(let i=0;i<=45;i++){const x=-1.2+2.4*i/45,zz=z*.24,y=.28*Math.sin(3*Math.hypot(x,zz));pts.push(proj([x,y,zz],ax,-ay*.5,3.8,.25,.72))}path(ctx,r,pts,GREEN,1)}for(const [x,n] of [[-3.5,'Box3D'],[-1.15,'Sphere'],[1.45,'Torus'],[3.8,'Surface3D']])label(ctx,r,x,-2.05,n,MUTED,14);}));return final(scene,7);}

export const janimDemos={frame_effect_example,mask_example,suite,three_d_shapes_example};
